import assert from 'node:assert/strict';
import fs from 'node:fs';
import { ECG_ELECTRODES } from '../src/ui/ecgLeadPlacement.js';
import { mountEmbeddedVitalsMonitor, stopEmbeddedVitalsMonitor } from '../src/vitalsMonitor.js';

const byId = Object.fromEntries(ECG_ELECTRODES.map((e) => [e.id, e]));
assert.equal(byId.RA.colorName, 'Red');
assert.equal(byId.LA.colorName, 'Yellow');
assert.equal(byId.RL.colorName, 'Black');
assert.equal(byId.LL.colorName, 'Green');
assert.ok(byId.RA.x > 24 && byId.RA.x < 29 && byId.RA.y > 50, 'red arm clip must sit on the patient wrist/forearm, not float outside');
assert.ok(byId.LA.x > 71 && byId.LA.x < 76 && byId.LA.y > 50, 'yellow arm clip must sit on the patient wrist/forearm, not float outside');
assert.ok(byId.V6.x < 66, 'V6 must remain on the lateral chest rather than the arm');
assert.ok(byId.RL.x < 50, 'black RL clip must sit on patient-right / viewer-left');
assert.ok(byId.LL.x > 50, 'green LL clip must sit on patient-left / viewer-right');
assert.ok(byId.V1.y < 30 && byId.V2.y < 30, 'V1/V2 must remain on the thorax');
assert.ok(byId.V4.y < 33 && byId.V6.y < 33, 'V4–V6 must remain on the chest, not abdomen');
const ecgSource = fs.readFileSync(new URL('../src/ui/ecgLeadPlacement.js', import.meta.url), 'utf8');
assert.ok(ecgSource.includes('top:${item.y}%'), 'placed electrodes must use percentage top coordinates');
assert.ok(ecgSource.includes('limb-clip-jaw'), 'limb electrodes must render as clips');
assert.ok(ecgSource.includes("item.id.replace('V', '')"), 'chest lead UI must show numbers without V prefix');
const css = fs.readFileSync(new URL('../styles.css', import.meta.url), 'utf8');
assert.ok(css.includes('body[data-patient-workspace="investigations"] .patient-rail { display:none !important; }'));
assert.ok(css.includes('.embedded-monitor-canvas'));
assert.equal(typeof mountEmbeddedVitalsMonitor, 'function');
assert.equal(typeof stopEmbeddedVitalsMonitor, 'function');
const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
assert.ok(html.includes('investigationEmptyWindow'));
assert.ok(html.includes('monitorWorkspaceWindow'));
console.log('PT-v9 ECG marker + embedded monitor tests passed');
