import assert from 'node:assert/strict';
import fs from 'node:fs';
import { getPhysicalExamMap } from '../src/data/physicalExamMap.v6.js';
import { ECG_ELECTRODES, createEcgLeadPlacementState } from '../src/ui/ecgLeadPlacement.v12.js';

const map=getPhysicalExamMap({id:'chest_pain_acs_risk'});
const byId=Object.fromEntries(map.hotspots.map(p=>[p.id,p]));
for(const id of ['lung-back-r-upper','lung-back-l-upper','lung-back-r-mid','lung-back-l-mid','lung-back-r-base','lung-back-l-base']) assert.ok(byId[id]);
assert.ok(byId['lung-back-r-upper'].positions.auscultate.y < 24,'upper posterior lung should be high on thorax');
assert.ok(byId['lung-back-r-mid'].positions.auscultate.y < 29,'mid posterior lung should be above prior low placement');
assert.ok(byId['lung-back-r-base'].positions.auscultate.y < 35,'posterior base should remain on lower thorax, not lumbar region');
assert.ok(byId['back-sacral'].y < 45,'sacral oedema target should be over sacrum rather than buttock/upper thigh');
assert.ok(byId['back-renal-angle-right'] && byId['back-renal-angle-left'],'bilateral renal tapotement points required');
assert.ok(byId['back-renal-angle-right'].tools.includes('palpate'));
assert.equal(ECG_ELECTRODES.length,10,'12-lead ECG requires 10 electrodes');
for(const id of ['RA','LA','RL','LL','V1','V2','V3','V4','V5','V6']) assert.ok(ECG_ELECTRODES.some(e=>e.id===id));
assert.equal(Object.keys(createEcgLeadPlacementState().placed).length,0);
assert.ok(fs.existsSync(new URL('../assets/peter_novak_front_52_v6.png', import.meta.url)));
assert.ok(fs.existsSync(new URL('../assets/peter_novak_back_52_v6.png', import.meta.url)));
const ui=fs.readFileSync(new URL('../src/ui/interactivePhysicalExam.v6.js',import.meta.url),'utf8');
assert.ok(!ui.includes('exam-current-finding'), 'duplicate current finding card must be removed');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
assert.ok(html.includes('ecgPlacementPanel'));
console.log('PT-v6 focused exam + ECG tests passed');
